services:
  postgres:
    image: postgres:18
    container_name: moveflow-postgres

    environment:
      POSTGRES_DB: moveflow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: moveflow

    ports:
      - "5433:5432"

    volumes:
      - moveflow_data:/var/lib/postgresql

volumes:
  moveflow_data: