spring.application.name=MoveFlow
spring.datasource.url=jdbc:postgresql://localhost:5432/moveflow
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update