spring.datasource.url=jdbc:postgresql://localhost:5433/moveflow
spring.datasource.username=postgres
spring.datasource.password=moveflow

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true